spring:
  application:
    name: friend-service
  mongodb:
    host: ${MONGODB_HOST:localhost}
    port: ${MONGODB_PORT:27017}
    username: ${MONGODB_USERNAME:mongodb}
    password: ${MONGODB_PASSWORD:123456789}
    database: ${MONGODB_DATABASE:jeri_friend_service}
server:
  port: ${SERVER_PORT:11004}
  servlet:
    context-path: /friend
minio:
  endpoint: http://${MINIO_HOST:localhost}:${MINIO_PORT:9000}
  accessKey: ${MINIO_ACCESS_KEY:admin}
  secretKey: ${MINIO_SECRET_KEY:admin}
  bucket-name: ${MINIO_BUCKET_NAME:jeri-friend-bucket}