spring:
  application:
    name: user-service
  flyway:
    enabled: true
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:100.69.244.58}:${DB_PORT:5432}/${DB_NAME:jeri_user_service}
    user: ${DB_USER:postgres}
    password: ${DB_PASSWORD:123456789}
    validate-migration-naming: true
    validate-on-migrate: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:100.69.244.58}:${DB_PORT:5432}/${DB_NAME:jeri_user_service}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:123456789}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          realm: ${KEYCLOAK_REALM:jeri-app-chat-realm}
          admin-username: ${KEYCLOAK_ADMIN_USERNAME:jeri-user-admin}
          admin-password: ${KEYCLOAK_ADMIN_PASSWORD:123456789}
          default-path: http://${KEYCLOAK_HOST:100.69.244.58}:${KEYCLOAK_PORT:8081}
          issuer-uri: ${spring.security.oauth2.resourceserver.jwt.default-path}/realms/jeri-app-chat-realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
server:
  port: ${SERVER_PORT:11001}
  servlet:
    context-path: /user
minio:
  endpoint: http://${MINIO_HOST:100.69.244.58}:${MINIO_PORT:9000}
  accessKey: ${MINIO_ACCESS_KEY:admin}
  secretKey: ${MINIO_SECRET_KEY:123456789}
  bucket-name: ${MINIO_BUCKET_NAME:jeri-user-bucket}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:11050}/eureka/
  instance:
    prefer-ip-address: true