name: jeri-app-chat
services:
    keycloak:
        container_name: keycloak
        image: keycloak/keycloak:26.5
        environment:
            KC_BOOTSTRAP_ADMIN_USERNAME: admin
            KC_BOOTSTRAP_ADMIN_PASSWORD: admin
        ports:
            - 8081:8080
        command:
            - start-dev
        networks:
            - jeri-app-chat-network

    elasticsearch:
        container_name: elastichsearch
        image: elasticsearch:9.2.4
        environment:
            - discovery.type=single-node
        ports:
            - 9200:9200
            - 9300:9300
        networks:
            - jeri-app-chat-network

    minio:
        container_name: minio
        image: minio/minio:latest
        environment:
            MINIO_DEFAULT_BUCKETS: admin
            MINIO_ROOT_USER: admin
            MINIO_ROOT_PASSWORD: 123456789
        command: [ "server", "--console-address", ":9001", "/data" ]
        ports:
            - 9000:9000
            - 9001:9001
        networks:
            - jeri-app-chat-network
    
    postgres:
        container_name: postgres
        image: postgres:15.1
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123456789
            POSTGRES_DB: postgres
        ports:
            - 5432:5432
        networks:
            - jeri-app-chat-network

    api-gateway:
        container_name: api-gateway
        build:
            context: ./backend/api-gateway
            dockerfile: Dockerfile
        ports:
            - 11000:11000
        environment:
            SERVER_PORT: 11000
        restart: always
        networks:
            - jeri-app-chat-network

    user-service:
        container_name: user-service
        build:
            context: ./backend/user-service
            dockerfile: Dockerfile
        ports:
            - 11001:11001
        environment:
            SERVER_PORT: 11001
            DB_HOST: postgres
            DB_PORT: 5432
            DB_NAME: jeri_user_service
            DB_USER: postgres
            DB_PASSWORD: 123456789
            MINIO_HOST: minio
            MINIO_PORT: 9000
            MINIO_ACCESS_KEY: admin
            MINIO_SECRET_KEY: 123456789
            MINIO_BUCKET_NAME: jeri-user-service
        networks:
            - jeri-app-chat-network
        depends_on:
            - postgres
            - minio
            - keycloak
            - api-gateway
    
    frontend:
        container_name: jeri_website
        build:
            context: ./frontend/website
            dockerfile: Dockerfile
        ports:
            - "80:80"
        depends_on:
            - api-gateway
        networks:
            - jeri-app-chat-network
        
networks:
    jeri-app-chat-network:
        driver: bridge