CREATE TABLE addresses
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    note             VARCHAR(255),
    deleted          BOOLEAN                  DEFAULT FALSE  NOT NULL,
    created_at       TIMESTAMP WITH TIME ZONE DEFAULT NOW()  NOT NULL,
    last_modified_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()  NOT NULL,
    created_by       VARCHAR(50)                             NOT NULL,
    last_modified_by VARCHAR(50)                             NOT NULL,
    version          BIGINT                   DEFAULT 0      NOT NULL,
    user_id          BIGINT                                  NOT NULL,
    street           VARCHAR(50),
    ward             VARCHAR(50),
    district         VARCHAR(50),
    city             VARCHAR(50),
    country          VARCHAR(50),
    postal_code      INTEGER,
    CONSTRAINT pk_addresses PRIMARY KEY (id)
);

CREATE TABLE users
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    note             VARCHAR(255),
    deleted          BOOLEAN                  DEFAULT FALSE  NOT NULL,
    created_at       TIMESTAMP WITH TIME ZONE DEFAULT NOW()  NOT NULL,
    last_modified_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()  NOT NULL,
    created_by       VARCHAR(50)                             NOT NULL,
    last_modified_by VARCHAR(50)                             NOT NULL,
    version          BIGINT                   DEFAULT 0      NOT NULL,
    first_name       VARCHAR(50)                             NOT NULL,
    last_name        VARCHAR(50)                             NOT NULL,
    birth_date       date                                    NOT NULL,
    gender           VARCHAR(255)                            NOT NULL,
    phone            VARCHAR(30)                             NOT NULL,
    email            VARCHAR(150)                            NOT NULL,
    username         VARCHAR(50)                             NOT NULL,
    avatar           VARCHAR(100),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE addresses
    ADD CONSTRAINT uc_addresses_user UNIQUE (user_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_phone UNIQUE (phone);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE addresses
    ADD CONSTRAINT FK_ADDRESSES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);