spring:
  application:
    name: feed-service
  mongodb:
    username: ${MONGODB_USERNAME:feed_user}
    password: ${MONGODB_PASSWORD:feed_password}
    host: ${MONGODB_HOST:localhost}
    port: ${MONGODB_PORT:27017}
    database: ${MONGODB_DATABASE:feed_db}
server:
  port: ${SERVER_PORT:11003}
  servlet:
    context-path: /feed
minio:
  endpoint: http://${MINIO_HOST:localhost}:${MINIO_PORT:9000}
  accessKey: ${MINIO_ACCESS_KEY:admin}
  secretKey: ${MINIO_SECRET_KEY:admin}
  bucket-name: ${MINIO_BUCKET_NAME:jeri-feed-bucket}